services:
    ger.autoresponder.listener:
        class: ger\autoresponder\event\main_listener
        arguments:
            - '@user'
            - '@auth'
            - '@dbal.conn'
            - '@request'            
        tags:
            - { name: event.listener }
